[package]
name = "mrubyedge-cli"
version = "0.9.0-rc1"
edition = "2024"

[[bin]]
name = "mrbedge"
path = "src/main.rs"

[dependencies]
clap = { version = ">= 4.5", features = ["derive"] }
mruby-compiler2-sys = "0.1.0"
